name: deploy-vitepress-to-pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build and deploy VitePress website
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
      - name: Run build
        run: |
          npm install
          npm run docs:build
      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v2
